### PR TITLE
[MERGE] branch Doxygen_generation into main

### PR DESCRIPTION
**Pull request by HenraL**
The workflows the branch was intended for have now been developed, the branch can remain open in case the workflows need minor tweaking.

The major changes are:
- The doxygen_generator only runs when:
  - There is a push on the branch doxygen_generator
  - The is a tag that is pushed
- The code_checker_and_mirrorer only runs when there is a push or a pull request.
  This workflow will run regardless of the branch pushing
  
The versioning is built in the following way:
vX.X.X
v -> version
X -> Major
X -> Minor
X -> Patch/Bug Fix/Retro-compatibility

### CODE REVIEW

**Review by Mord0rak — APPROVED** [review]
Looks good to me.
Just one question
> What are the tags for doxygen_generator ?

**Review by KomiWolf — APPROVED** [review]
Good

**Comment by HenraL** [comment]
@Mord0rak 

> Looks good to me. Just one question
> 
> > What are the tags for doxygen_generator ?

The doxygen generator branch is intended for developping the workflows, the doxygen workflow, only publishes a package if it was triggered by a tag, otherwise, only the webpage is updated (which also occurs on the push trigger).
The versioning is because when one wishes to create a release, they can only do so if a tag exists, thus the reason why packages are only published when a tag is provided.

Regarding the tag structure, it is explained in the initial pull request comment:
> vX.X.X
> v -> version
> X -> Major
> X -> Minor
> X -> Patch/Bug Fix/Retro-compatibility

This is linked to the development process of the app.
Rewrote big chunks of the program -> increase the first digit
Add a new feature -> increase the second digit
patched something, fixed a bug, re-implemented old non-latest functions -> increase the last digit


Hope this comment answers your question.

**Comment by Harleen-sk** [comment]
okay, good

**Review by Harleen-sk — APPROVED** [review]

**Review by OrionPX4k — APPROVED** [review]

**Pull request merged**
